Improve my surveys component
InseeFr/Coleman-My-Surveys pull request #2
Opened 2022-11-03 12:22 UTC by EricThuaud

2022-11-03 13:20 UTC, laurentC35 requested changes
I have reviewed your code.
Well done !

But I have some requests for you.

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/components/UserAccount/personalData/display.jsx
> +  const fonction = user.function;
You can write
```js
const { lastName, firstName, phone, function: userFunction } = user
```

This allows to rename the problematic word "function" as "userFunction".

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/shared/Header/index.jsx
> +            <Link>
You can now remove the `<Link>` tag here.
It is useless now :-)

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/components/SurveyList/item/index.jsx
> +  const getLogoType = () => {
Can you create a new component for the Logo to externalize this ?
You can create the Icon under "item" folder like `itemIcon.jsx`

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/components/SurveyList/item/index.jsx
> +      getSurveyStatus((openingDate, closingDate, returnDate).status === surveyDictionary.surveyClosing)
You call 4 times the function `getSurveyStatus` !
If you externalize the logo, you can comute the result only one time according to the parameters

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/components/SurveyList/filter.jsx
> +            <InputLabel id="demo-multiple-chip-label">{surveyDictionary.searchByStatus}</InputLabel>
You have the same id, I think you have to rename it (`id="demo-multiple-chip-label"`)

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/components/SurveyList/filter.jsx
> +  const statusOrder = [
You can externalize this into core/constants in the file like `filterConstants.js`

2022-11-03 13:20 UTC, laurentC35 commented on src/ui/components/SurveyList/filter.jsx
> +  const sortByQuestioningStatusBySurveyStatusByReturnDate = (a, b) => {
This function has to be externalize into `core/functions.js`

2022-11-03 13:25 UTC, EricThuaud commented on src/ui/components/SurveyList/item/index.jsx
> +    return "nothing";
yep^^ corrected

2022-11-03 13:44 UTC, laurentC35 commented
I have another detail.
Can you change the favicon.ico, logo192.png and logo512.png (under public folder) to the logo of marianne ?

- update `manifest.json file`  :

```json
{
"short_name" : "Portail Mes Enquêtes", 
"name" : "Portail de réponse aux enquêtes de la statistique publique",
...
}
```
- update `index.html` file

```xml
<head>
  ...
  <meta
      name="description"
      content="Portail de réponse aux enquêtes de la statistique publique" />
  ...
  </head>
```

2022-11-03 13:50 UTC, EricThuaud commented on src/ui/shared/Header/index.jsx
> +            <Link>
done

2022-11-03 13:51 UTC, EricThuaud commented on src/core/functions.js
> +    colorChip = "error";
done

2022-11-03 14:11 UTC, EricThuaud commented on src/ui/components/SurveyList/filter.jsx
> +  const sortByQuestioningStatusBySurveyStatusByReturnDate = (a, b) => {
done

2022-11-03 14:31 UTC, EricThuaud commented on src/ui/components/SurveyList/item/index.jsx
> +  const getLogoType = () => {
done, but keeping getLogoType function in itemIcon.jsx, returning getLogoType()

2022-11-03 14:31 UTC, EricThuaud commented on src/ui/components/SurveyList/item/index.jsx
> +      getSurveyStatus((openingDate, closingDate, returnDate).status === surveyDictionary.surveyClosing)
done

2022-11-04 09:37 UTC, laurentC35 approved these changes
Some improvements can be made.
But I think it's enough for now :)

Good work

2022-11-04 09:38 UTC, merged